import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Providers from "./Providers";


export const metadata: Metadata = {
  title: "ICODER - Limón",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <Providers>
          <Navbar>
            {children}
          </Navbar>
        </Providers>

      </body>
    </html>
  );
}
